language: objective-c
before_install:
    - gem install xctest-runner
    - gem install xcpretty
script:
    - xctest-runner -project OPBitMaskNumber.xcodeproj -scheme OPBitMaskNumberTests | xcpretty -c